spring:
  data:
    redis:
      .ser
  docker:
    compose:
      enabled: false
  application:
    name: traffic-gateway
  config:
    import: "consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
  threads:
    virtual:
      enabled: true


server:
  tomcat:
    threads:
      max: 10
  redis:
    bucket:
      host: 127.0.0.1
      port: 6379
    waiting:
      host: 127.0.0.1
      port: 6379
    active:
      host: 127.0.0.1
      port: 6379

#  Key / Values
#  config/traffic-gateway/gate/gateA
#  {
#    "GateId": "1313131311",
#    "GateName": "B 경로",
#    "ServiceId": 2,
#     "GateTps": 3
#  }