spring:
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
  docker:
    compose:
      enabled: false
  application:
    name: traffic-gateway
  config:
    import: "consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
  threads:
    virtual:
      enabled: true

server:
  redis:
    bucket:
      host: 127.0.0.1
      port: 6379
    waiting:
      host: 127.0.0.1
      port: 6379
    active:
      host: 127.0.0.1
      port: 6379

